language: android
dist: trusty

env:
  global:
    - TARGET_VERSION=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.2
    - ANDROID_HOME=~/android-sdk

before_script:
  - chmod +x gradlew

before_install:
  - chmod +x gradlew

# downloading updated command line tools and moved inside SDK folder
  - touch $HOME/.android/repositories.cfg
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip" -O commandlinetools.zip
  - unzip commandlinetools.zip -d $ANDROID_HOME/
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-${TARGET_VERSION}" --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" --sdk_root=$ANDROID_HOME

  - yes | sdkmanager "build-tools;30.0.2"
  - yes | sdkmanager "platforms;android-$TARGET_VERSION"

android:
  components:
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$TARGET_VERSION
    - tools
    - extra
    - extra-android-m2repository
    - extra-google-m2repository

#add jdk 11 as gradle plugin version on travis is 7.0.2
jdk:
  - openjdk11
script:
  - ./gradlew build