language: android
# Linux
dist: trusty

#make gradle executable
before_install:
  - chmod +x gradlew
  #accept licenses
  - yes | sdkmanager "platforms;android-30"
  - yes | sdkmanager --licenses

android:
  components:
    - android-30
    - extra

#add jdk 11 as gradle plugin version on travis is 7.0.2
jdk:
  - openjdk11