language: android
# Linux
dist: trusty

#make gradle executable
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "build-tools;30.0.2"
  - yes | sdkmanager "platforms;android-30"

android:
  components:
    - build-tools-30.0.2
    - android-30
    - tools
    - tools
    - extra

#add jdk 11 as gradle plugin version on travis is 7.0.2
#jdk:
  - oraclejdk11