language: android
dist: trusty
env:
  global:
  - TARGET_VERSION=30
  - ANDROID_BUILD_TOOLS_VERSION=30.0.2
  - ANDROID_HOME=~/android-sdk
before_script:
- chmod +x gradlew
before_install:
- openssl aes-256-cbc -K $encrypted_d8091b9e0b78_key -iv $encrypted_d8091b9e0b78_iv
  -in readdit.jks.enc -out readdit.jks -d
- chmod +x gradlew
- touch $HOME/.android/repositories.cfg
- wget "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip"
  -O commandlinetools.zip
- unzip commandlinetools.zip -d $ANDROID_HOME/
- yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-${TARGET_VERSION}"
  --sdk_root=$ANDROID_HOME
- yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}"
  --sdk_root=$ANDROID_HOME
android:
  components:
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$TARGET_VERSION
  - tools
  - extra
  - extra-android-m2repository
  - extra-google-m2repository
# branches travis will look into
branches:
  only:
    - master
# deployment
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: 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
  file_glob: true
  file: /home/travis/build/philipjan/Readdit/app/release/*
  on:
    repo: philipjan/Readdit
    tags: true
jdk:
- openjdk11
script:
- "./gradlew build"