language: android
# Linux
dist: trusty

#make gradle executable
before_install:
  - chmod +x gradlew
  #accept licenses
  - yes | sdkmanager "build-tools;31.0.0"

android:
  components:
    - android-30
    - extra
    - build-tools-31.0.0

#add jdk 11 as gradle plugin version on travis is 7.0.2
jdk:
  - openjdk11