language: android
dist: trusty

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "build-tools;30.0.2"
  - yes | sdkmanager "platforms;android-30"

android:
  components:
    - platform-tools
    - build-tools-30.0.2
    - android-30
    - tools
    - extra
#add jdk 11 as gradle plugin version on travis is 7.0.2
jdk:
  - openjdk11